# Generated by Django 4.2.6 on 2023-11-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intern',
            fields=[
                ('emp_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('clg_name', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('passing_year', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('finishing_date', models.DateField()),
            ],
        ),
    ]
